Repository MeikelLP/quantum-core-x, pull requests merged in 2024-10, with the labels that each got.

#169 chore: Add repo files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: type/chore

#170 fix(game): Dropping item
  src/Data/Game.Persistence/ItemRepository.cs
  src/Executables/Game/Extensions/ItemExtensions.cs
  src/Executables/Game/World/Entities/PlayerEntity.cs
Labels: type/bug

#161 Implement "Already Logged In" and Refactor Redis
  src/Data/Core.Caching/CacheManager.cs
  src/Data/Core.Caching/CacheStoreType.cs
  src/Data/Core.Caching/Core.Caching.csproj
  src/Data/Core.Caching/ExpiresIn.cs
  src/Data/Core.Caching/Extensions/ServiceExtensions.cs
  src/Data/Core.Caching/ICacheManager.cs
  src/Data/Core.Caching/IRedisStore.cs
  src/Data/Core.Caching/RedisStore.cs
  src/Data/Game.Caching/CachePlayerRepository.cs
  src/Data/Game.Persistence/ItemRepository.cs
  src/Executables/Auth/PacketHandlers/LoginRequestHandler.cs
  src/Executables/Game/ChatManager.cs
  src/Executables/Game/Commands/LogoutCommand.cs
  src/Executables/Game/Extensions/ItemExtensions.cs
  src/Executables/Game/Extensions/ServiceExtensions.cs
  src/Executables/Game/GameConnection.cs
  src/Executables/Game/GameServer.cs
  src/Executables/Game/ISessionManager.cs
  src/Executables/Game/PacketHandlers/Loading/EnterGameHandler.cs
  src/Executables/Game/PacketHandlers/Select/EmpireHandler.cs
  src/Executables/Game/PacketHandlers/TokenLoginHandler.cs
  src/Executables/Game/PlayerUtils/QuickSlotBar.cs
  src/Executables/Game/SessionManager.cs
  src/Executables/Game/World/Entities/PlayerEntity.cs
  src/Libraries/Game.Commands/CommandManager.cs
  src/Tests/Game.Tests/PlayerManagerTests.cs
Labels: type/enhancement, area/game, area/dev

#175 fix(seed): empire selection when fresh instance
  src/CorePluginAPI/Game/Types/EEmpire.cs
  src/Data/Game.Persistence/Migrations/Mysql/20240604163310_Initial.cs
  src/Data/Game.Persistence/Migrations/Postgresql/20240604163418_Initial.cs
  src/Data/Game.Persistence/Migrations/Sqlite/20240604163400_Initial.cs
Labels: type/bug

#176 Revert "ci: implement conventional commit PR checker"
  .github/workflows/validate-pr.yml
Labels: type/bug, area/ci

#182 feat: add all-contributors
  .all-contributorsrc
  AUTHORS.md
  README.md
Labels: type/feature

#179 fix(game): calculate movement & attack speed
  src/Executables/Game/PlayerUtils/EItemType.cs
  src/Executables/Game/World/Entities/PlayerEntity.cs
Labels: type/enhancement, type/feature, area/game

#178 fix: update spawning behavior for fixed NPCs
  src/CorePluginAPI/Core/Models/EAiFlags.cs
  src/CorePluginAPI/Core/Models/MonsterData.cs
  src/Executables/Game/Services/ParserService.cs
  src/Executables/Game/World/Map.cs
  src/Executables/Game/World/SpawnPoint.cs
  src/Tests/Core.Tests/MapTests.cs
Labels: type/enhancement, area/game

#190 Basic observability
  src/Executables/Game/GameServer.cs
  src/Executables/Game/World/Map.cs
  src/Executables/Game/World/World.cs
Labels: type/feature, area/game
